### ISSUE TITLE
Panic when getting credential

### ISSUE THREAD

**Issue by emersion** [danieljoos/wincred#5]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x838dbe]

goroutine 35 [running]:
panic(0x95dd80, 0xc08200a0a0)
        C:/Go/src/runtime/panic.go:481 +0x3f4
github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred.nativeToCredential(0x0, 0xc08212e000)
        C:/Users/tablet-143/go/src/github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred/conver  sion.go:41 +0x4e
github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred.nativeCredRead(0xc08210e0f0, 0x27, 0x1, 0  x0, 0x0, 0x0)
        C:/Users/tablet-143/go/src/github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred/native  .go:73 +0x2b3
github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred.GetGenericCredential(0xc08210e0f0, 0x27,   0xc08210e112, 0x0, 0x0)
        C:/Users/tablet-143/go/src/github.com/ProtonMail/super-secret-project/vendor/github.com/danieljoos/wincred/wincre  d.go:9 +0x4a
github.com/ProtonMail/super-secret-project/vendor/github.com/docker/docker-credential-helpers/wincred.Wincred.Get(0xc0821  0e0f0, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by danieljoos** [comment]
Looking into it.

**Comment by danieljoos** [comment]
I'm not sure why this happens, but it looks like the [`CredRead`](http://msdn.microsoft.com/en-us/library/windows/desktop/aa374804(v=vs.85).aspx) function returned a _success_ state but the credentials pointer is still `NULL`. I added some checking for null pointers to the conversion routines (1c80202) + some tests (3da991f). This should at least fix the panic and instead returns `nil` as result.

**Comment by emersion** [comment]
It was indeed very strange. It seems to work now. Maybe it was a windows bug fixed in an update.

Thanks for your fix :)
